### ISSUE TITLE
When headers in a page start at the 2nd level and the next header is also 2nd level, it gets wrongly nested inside the previous one in the Table of Contents

### ISSUE THREAD

**Issue by alfredbaudisch** [alfredbaudisch/pardall_markdown_phoenix_demo#3]
This is not related to the framework, it's the table of contents HTML helper from this demo project that is dealing with this wrongly. Although this is a demo project and demo feature, this repository is as important as PardallMarkdown itself, since it shows a real application for the framework.

**This is probably going to be used by all Phoenix applications that use PardallMarkdown**, including my own Wiki, like the wrong nesting in the [About](https://pardall.xyz/about) page.

# Problem
Example Markdown:
```
%{
  title: "Page"
}
---

## Links
Content...

## More about me
About content...

## Wrong nesting
Nested content...
```

This is how the table of contents is being generated:
![image](https://user-images.githubusercontent.com/248383/134521307-b31915e7-52c4-45bb-b075-9338c4a50444.png)

# Expected
This is the expected result, since they are at the same level (h2):
![image](https://user-images.githubusercontent.com/248383/134521389-f3311431-c654-4381-b844-ec2f5ff330b1.png)

# Source
- Generate TOC: [pardall_markdown_helpers.ex#L195](https://github.com/alfredbaudisch/pardall_markdown_phoenix_demo/blob/master/lib/pardall_web/views/pardall_markdown_helpers.ex)
- Usage: [single_post.html.heex#L10](https://github.com/alfredbaudisch/pardall_markdown_phoenix_demo/blob/master/lib/pardall_web/templates/content/single_post.html.heex#L10)

**Comment by alfredbaudisch** [comment]
@rockchalkwushock  this one is a bit more challenging, if you want to take it, feel free to do so :) If not, I may take it by the end of the month.

**Comment by rockchalkwushock** [comment]
@alfredbaudisch I think I can take a stab at this one as well.
